### ISSUE TITLE
Add an example folder with sample forms

### ISSUE THREAD

**Issue by emeraldjava** [jbrinley/wp-forms#3]
Hey,

I think an examples folder with sample forms might be useful to explain some of the more complicated features of your framework. 

I'd be interested to see an example where the form elements are decorated in such a way that the final form would appear as a grid once css or js styling has been applied.

Regards,
Paul

**Comment by jbrinley** [comment]
I think it makes more sense to have a separate website dedicated to examples and recipes (the canonical documentation will still live in this repo, though). To that end: http://wpforms.xplus3.net/. It's a work in progress, and I'll be taking requests.

Addressing your specific question: this isn't really going to be a tutorial on CSS styling, but check out the recipe at http://wpforms.xplus3.net/posts/8/table-layout/ to see how to completely transform the HTML into an actual table.
