### ISSUE TITLE
Support FieldSet elements

### ISSUE THREAD

**Issue by emeraldjava** [jbrinley/wp-forms#4]
It would be good if the WP_Form could support a FieldSet elements. This would allow groups of form elements to be grouped, so that css styling of the form could be more easily controlled.

A new WP_Form_Element_FieldSet would be created which would support the normal decorators. It would also support a list of form elements.

A new WP_Form_View_FieldSet would render the element, and then iterate the list of form elements calling render on each.

**Comment by jbrinley** [comment]
Definitely high up on my todo list.

**Comment by jbrinley** [comment]
Added in 3dc6bbf4f0aab132145da92c2f3781a030b20e80 (see docs at https://github.com/jbrinley/wp-forms/blob/develop/docs/elements.md#fieldset)
